### ISSUE TITLE
Programming suggestions

### ISSUE THREAD

**Issue by bpbond** [JGCRI/trackingC#62]
1. In general don't `rm(list = ls())`. First, it's not friendly to users ("argh, this script deleted every object in my workspace!"). Second, there's no point; your code is in Rmd files and thus generally run in a separate R instance that's shut down when the document is rendered.
2. Rather than have (e.g.) "0.33" appear in many places—which is confusing, risks inconsistency, and is a pain to change—use a _named constant_ defined in a single place. This makes the code clearer and more robust.

Science note:
1. **Always visualize your data**. See the PR I'm about to open.

**Comment by leeyap** [comment]
1. Ah, I never knit the files when I'm working in them. I like the RMarkdown formatting just because of the chunks, but not for knitting the whole thing - it takes way too long and just isn't practical for testing. Noted, though, and I will keep those lines out.
2. Done. 
3. Thanks for looking into that! Don't know why we didn't figure that out sooner, but oh well.

**Comment by bpbond** [comment]
Sounds good. I may follow up about no. 3 above when we talk next, but for now 🎉
